In [1]:
#Importar librerias necesarias
import pandas as pd

In [2]:
#Carga desde un archivo .csv sin indice y eliminar filas innecesarias
Madrid=pd.read_csv("Listings Final-Madrid.csv")
Madrid

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,1104967621421098322,https://www.airbnb.com/rooms/1104967621421098322,20240615011404,2024-06-15,city scrape,"Habitación de lujo, baño privado",NaN,NaN,https://a0.muscache.com/pictures/miso/Hosting-...,565307927,...,5.00,5.00,5.00,NaN,f,1,0,1,0,0.61
1,930941073152690361,https://www.airbnb.com/rooms/930941073152690361,20240615011404,2024-06-15,city scrape,habitación para pareja,Rent room for loose nights or weekends to a c...,NaN,https://a0.muscache.com/pictures/85f0b383-e8f8...,442944608,...,5.00,4.67,5.00,NaN,f,2,0,2,0,0.28
2,51647382,https://www.airbnb.com/rooms/51647382,20240615011404,2024-06-15,city scrape,Buenos Aires en Madrid,"This special place is close to everything, mak...",The neighborhood is m,https://a0.muscache.com/pictures/db018af4-f622...,252336445,...,4.83,4.51,4.61,NaN,t,2,0,2,0,5.40
3,1026072412626070839,https://www.airbnb.com/rooms/1026072412626070839,20240615011404,2024-06-15,city scrape,Habitación Madrid Rio!,Enjoy the simplicity of this quiet and central...,NaN,https://a0.muscache.com/pictures/miso/Hosting-...,545435841,...,5.00,5.00,5.00,NaN,f,1,0,1,0,0.14
4,766423030884644417,https://www.airbnb.com/rooms/766423030884644417,20240615011404,2024-06-15,city scrape,habitación para turista,Enjoy a stylish experience at this centrally-l...,NaN,https://a0.muscache.com/pictures/miso/Hosting-...,3882456,...,NaN,NaN,NaN,NaN,f,1,0,1,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26919,47901684,https://www.airbnb.com/rooms/47901684,20240615011404,2024-06-15,previous scrape,Habitacion doble dos camas individuales,"Private rooms in HOSTAL SAN BLAS, located at C...",It is an area with a predominance of cultural ...,https://a0.muscache.com/pictures/50a4abf3-d0e4...,385964459,...,4.89,5.00,4.00,NaN,f,3,0,3,0,0.22
26920,36095034,https://www.airbnb.com/rooms/36095034,20240615011404,2024-06-15,city scrape,Generator - Family Room for 4,Keeping family first with this room for four.<...,Generator Madrid is located in the heart of th...,https://a0.muscache.com/pictures/3d74ee5d-546e...,270258576,...,4.66,4.98,4.58,A78484961,t,5,0,3,2,0.93
26921,31983597,https://www.airbnb.com/rooms/31983597,20240615011404,2024-06-15,city scrape,Madrid- Luxury Apartment · SOL-GRAN VÍA - L9,Spectacular apartment located in a classic bui...,"The city of Madrid, capital of Spain, is one o...",https://a0.muscache.com/pictures/5d5e8796-3b24...,5188527,...,4.80,4.90,4.39,NaN,t,2,2,0,0,2.36
26922,1083323735523972892,https://www.airbnb.com/rooms/1083323735523972892,20240615011404,2024-06-15,city scrape,Acogedor apartamento en Sol,This cute one-bedroom apartment is located in ...,NaN,https://a0.muscache.com/pictures/miso/Hosting-...,410032768,...,5.00,5.00,5.00,NaN,t,2,2,0,0,0.29
26923,655448045703760486,https://www.airbnb.com/rooms/655448045703760486,20240615011404,2024-06-15,city scrape,Precioso apartamento en el centro.,"DESIGNED FOR you, so you can get to know our a...",Madrid is one of the most iconic cities in Spa...,https://a0.muscache.com/pictures/miso/Hosting-...,394687867,...,4.63,4.72,4.43,NaN,t,66,66,0,0,1.91

In [7]:
#Identificar valores nulos por columna
# Ajustar maximo de filas
pd.options.display.max_rows = None
Valores_Nulos=Madrid.isnull().sum()
Columnas_Con_Nulos = Valores_Nulos[Valores_Nulos > 0]
Columnas_Con_Nulos

description                      966
neighborhood_overview          13618
picture_url                        2
host_name                          4
host_since                         4
host_location                   8416
host_about                     13945
host_response_time              4915
host_response_rate              4915
host_acceptance_rate            4017
host_is_superhost                155
host_thumbnail_url                 4
host_picture_url                   4
host_neighbourhood             17204
host_listings_count                4
host_total_listings_count          4
host_verifications                 4
host_has_profile_pic               4
host_identity_verified             4
neighbourhood                  13618
bathrooms                       5326
bathrooms_text                    36
bedrooms                        2212
beds                            5359
price                           5304
calendar_updated               26924
has_availability                1536
first_review                    5856
last_review                     5856
review_scores_rating            5856
review_scores_accuracy          5897
review_scores_cleanliness       5898
review_scores_checkin           5898
review_scores_communication     5897
review_scores_location          5900
review_scores_value             5901
license                        24182
reviews_per_month               5856
dtype: int64

In [11]:
#Información tipos de columnas
Tipos_Columnas = Madrid[Columnas_Con_Nulos.index].dtypes
Columnas_Object = Tipos_Columnas[Tipos_Columnas == 'object']
Columnas_Object

description               object
neighborhood_overview     object
picture_url               object
host_name                 object
host_since                object
host_location             object
host_about                object
host_response_time        object
host_response_rate        object
host_acceptance_rate      object
host_is_superhost         object
host_thumbnail_url        object
host_picture_url          object
host_neighbourhood        object
host_verifications        object
host_has_profile_pic      object
host_identity_verified    object
neighbourhood             object
bathrooms_text            object
price                     object
has_availability          object
first_review              object
last_review               object
license                   object
dtype: object

In [14]:
#Información tipos de columnas
Tipos_Columnas = Madrid[Columnas_Con_Nulos.index].dtypes
Columnas_Object = Tipos_Columnas[Tipos_Columnas == 'float']
Columnas_Object

host_listings_count            float64
host_total_listings_count      float64
bathrooms                      float64
bedrooms                       float64
beds                           float64
calendar_updated               float64
review_scores_rating           float64
review_scores_accuracy         float64
review_scores_cleanliness      float64
review_scores_checkin          float64
review_scores_communication    float64
review_scores_location         float64
review_scores_value            float64
reviews_per_month              float64
dtype: object

In [15]:
#Realizamos una copia del dataframe
copia_Madrid = Madrid.copy()

In [16]:
#Cuarto método de sustitución de valores nulos
#Sustituir valores nulos por un string en  concreto
copia_Madrid["description"] = copia_Madrid["description"].fillna("DESCRIPCIÓN FALTANTE")
copia_Madrid["neighborhood_overview"] = copia_Madrid["neighborhood_overview"].fillna("SIN INFORMACIÓN")
copia_Madrid["picture_url"] = copia_Madrid["picture_url"].fillna("SIN IMAGEN")
copia_Madrid["host_name"] = copia_Madrid["host_name"].fillna("SIN NOMBRE")
copia_Madrid["host_since"] = copia_Madrid["host_since"].fillna("SIN FECHA")
copia_Madrid["host_location"] = copia_Madrid["host_location"].fillna("SIN INFORMACIÓN")
copia_Madrid["host_about"] = copia_Madrid["host_about"].fillna("SIN INFORMACIÓN")
copia_Madrid["host_response_time"] = copia_Madrid["host_response_time"].fillna("SIN INFORMACIÓN")
copia_Madrid["host_response_rate"] = copia_Madrid["host_response_rate"].fillna("SIN INFORMACIÓN")
copia_Madrid["host_acceptance_rate"] = copia_Madrid["host_acceptance_rate"].fillna("SIN INFORMACIÓN")
copia_Madrid["host_is_superhost"] = copia_Madrid["host_is_superhost"].fillna("VALIDACIÓN PENDIENTE")
copia_Madrid["host_thumbnail_url"] = copia_Madrid["host_thumbnail_url"].fillna("MINIATURA NO DISPONIBLE")
copia_Madrid["host_picture_url"] = copia_Madrid["host_picture_url"].fillna("SIN IMAGEN")
copia_Madrid["host_neighbourhood"] = copia_Madrid["host_neighbourhood"].fillna("SIN INFORMACIÓN")
copia_Madrid["host_verifications"] = copia_Madrid["host_verifications"].fillna("VALIDACIÓN PENDIENTE")
copia_Madrid["host_has_profile_pic"] = copia_Madrid["host_has_profile_pic"].fillna("INFORMACIÓN FALTANTE")
copia_Madrid["host_identity_verified"] = copia_Madrid["host_identity_verified"].fillna("INFORMACIÓN FALTANTE")
copia_Madrid["neighbourhood"] = copia_Madrid["neighbourhood"].fillna("SIN INFORMACIÓN")
copia_Madrid["bathrooms_text"] = copia_Madrid["bathrooms_text"].fillna("SIN INFORMACIÓN")
copia_Madrid["price"] = copia_Madrid["price"].fillna("NO DEFINIDO")
copia_Madrid["has_availability"] = copia_Madrid["has_availability"].fillna("INFORMACIÓN NO DISPONIBLE")
copia_Madrid["first_review"] = copia_Madrid["first_review"].fillna("SIN RESEÑA")
copia_Madrid["last_review"] = copia_Madrid["last_review"].fillna("SIN RESEÑA")
copia_Madrid["license"] = copia_Madrid["license"].fillna("SIN LICENCIA")

In [20]:
#Primer método de sustitución de valores nulos
#Sustituir valores nulos con promedio o media
copia_Madrid["review_scores_rating"]=copia_Madrid["review_scores_rating"].fillna(round(copia_Madrid ['review_scores_rating'].mean(),1))
copia_Madrid["review_scores_accuracy"]=copia_Madrid["review_scores_accuracy"].fillna(round(copia_Madrid ['review_scores_accuracy'].mean(),1))
copia_Madrid["review_scores_cleanliness"]=copia_Madrid["review_scores_cleanliness"].fillna(round(copia_Madrid ['review_scores_cleanliness'].mean(),1))
copia_Madrid["review_scores_checkin"]=copia_Madrid["review_scores_checkin"].fillna(round(copia_Madrid ['review_scores_checkin'].mean(),1))
copia_Madrid["review_scores_communication"]=copia_Madrid["review_scores_communication"].fillna(round(copia_Madrid ['review_scores_communication'].mean(),1))
copia_Madrid["review_scores_location"]=copia_Madrid["review_scores_location"].fillna(round(copia_Madrid ['review_scores_location'].mean(),1))
copia_Madrid["review_scores_value"]=copia_Madrid["review_scores_value"].fillna(round(copia_Madrid ['review_scores_value'].mean(),1))
copia_Madrid["reviews_per_month"]=copia_Madrid["reviews_per_month"].fillna(round(copia_Madrid ['reviews_per_month'].mean(),1))
copia_Madrid["host_listings_count"]=copia_Madrid["host_listings_count"].fillna(round(copia_Madrid ['host_listings_count'].mean(),1))
copia_Madrid["host_total_listings_count"]=copia_Madrid["host_total_listings_count"].fillna(round(copia_Madrid ['host_total_listings_count'].mean(),1))

In [21]:
#Tercer método de sustitución de valores nulos
#Sustituir valores nulos por un valor numérico en  concreto
copia_Madrid["bathrooms"]=copia_Madrid["bathrooms"].fillna("-")
copia_Madrid["bedrooms"]=copia_Madrid["bedrooms"].fillna("-")
copia_Madrid["beds"]=copia_Madrid["beds"].fillna("-")
copia_Madrid["calendar_updated"]=copia_Madrid["calendar_updated"].fillna("-")

In [22]:
#Corroboramos valores nulos
# Ajustar maximo de filas
pd.options.display.max_rows = None
valores_nulos=copia_Madrid.isnull().sum()
valores_nulos

id                                              0
listing_url                                     0
scrape_id                                       0
last_scraped                                    0
source                                          0
name                                            0
description                                     0
neighborhood_overview                           0
picture_url                                     0
host_id                                         0
host_url                                        0
host_name                                       0
host_since                                      0
host_location                                   0
host_about                                      0
host_response_time                              0
host_response_rate                              0
host_acceptance_rate                            0
host_is_superhost                               0
host_thumbnail_url                              0
host_picture_url                                0
host_neighbourhood                              0
host_listings_count                             0
host_total_listings_count                       0
host_verifications                              0
host_has_profile_pic                            0
host_identity_verified                          0
neighbourhood                                   0
neighbourhood_cleansed                          0
neighbourhood_group_cleansed                    0
latitude                                        0
longitude                                       0
property_type                                   0
room_type                                       0
accommodates                                    0
bathrooms                                       0
bathrooms_text                                  0
bedrooms                                        0
beds                                            0
amenities                                       0
price                                           0
minimum_nights                                  0
maximum_nights                                  0
minimum_minimum_nights                          0
maximum_minimum_nights                          0
minimum_maximum_nights                          0
maximum_maximum_nights                          0
minimum_nights_avg_ntm                          0
maximum_nights_avg_ntm                          0
calendar_updated                                0
has_availability                                0
availability_30                                 0
availability_60                                 0
availability_90                                 0
availability_365                                0
calendar_last_scraped                           0
number_of_reviews                               0
number_of_reviews_ltm                           0
number_of_reviews_l30d                          0
first_review                                    0
last_review                                     0
review_scores_rating                            0
review_scores_accuracy                          0
review_scores_cleanliness                       0
review_scores_checkin                           0
review_scores_communication                     0
review_scores_location                          0
review_scores_value                             0
license                                         0
instant_bookable                                0
calculated_host_listings_count                  0
calculated_host_listings_count_entire_homes     0
calculated_host_listings_count_private_rooms    0
calculated_host_listings_count_shared_rooms     0
reviews_per_month                               0
dtype: int64